title: sendevia 的博客
email: sendevialol@gmail.com
github_amix: https://github.com/Sendevia/AincradMix
current_version_amix: release1.0
timezone: Asia/Shanghai

bilibili: https://space.bilibili.com/84041790
twitter: https://twitter.com/sendevia

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tsc

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
  - _redirects
  - sendevia.github.io.code-workspace
  - .typescript

typescript:
  temp_dir: .typescript
  extensions: [".ts", ".tsx"]
  copy_ext: []
  command: ["tsc"]
  cache: true
