title: sendevia 的博客
email: sendevialol@gmail.com
github: https://github.com/Sendevia/sendvia.github.io
github_amix: https://github.com/Sendevia/AincradMix
current_version_amix: release1.0
timezone: Asia/Shanghai

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
