title: AincradMix
email: sendevialol@gmail.com
github: https://github.com/Sendevia/AincradMix
timezone: Asia/Shanghai
last_version: 210601-1.8a
current_version: master
release_version: 210601-1.8a

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
