title: AincradMix
email: sendevialol@gmail.com
twitter_username: sendevia
email: sendevialol@gmail.com
github_username: Sendevia
github: https://github.com/Sendevia/AincradMix
timezone: Asia/Shanghai

theme: 
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
 