version: "23.815.0"

title: "sendevia 的博客"
baseurl: ""
permalink: "/:title"
locale: "zh_CN"
timezone: "Asia/Shanghai"

author: "sendevia"
mugshot: "/assets/images/avatar.webp"
email: "me@sendevia.top"
github: "https://github.com/Sendevia"

impression: "/assets/images/100628112_p0.webp"

twitter:
  username: "sendevia"
  card: "summary"

defaults:
  - scope:
      path: ""
    values:
      layout: "Material3"
      published: true
  - scope:
      path: "_posts"
    values:
      permalink: "/:short_year/:month/:day/:title"
      toc: true

toc:
  item_class: "mnd-entry"
  item_prefix: "mnd-"
  list_class: "mnd-section"
  list_id: null
  max_level: 2
  ordered_list: false

markdown: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

webrick:
  headers:
    Cache-Control: "must-revalidate"

jekyll_timeago:
  depth: 2
  translations_path: "/_data/timeago.yml"
  default_locale: "zh_CN"
  available_locales:
    - "en"
    - "zh_CN"

last-modified-at:
  date-format: "%Y 年 %m 月 %d 日"

exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - node_modules/
  - package-lock.json
  - package.json
  - README.MD
  - sendevia.page.jekyll.code-workspace
  - tsconfig.json
  - vendor/
  - webpack.config.js
  - webpack/
