baseurl:
email: me@sendevia.top
github: https://github.com/Sendevia
header_image: /assets/images/102911375_p0.webp
locale: zh_CN
permalink: /:title
timezone: Asia/Shanghai
title: sendevia 的博客
twitter:
  username: sendevia
  card: summary

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      layout: Material3
      published: true
  - scope:
      path: _posts
    values:
      permalink: /:short_year/:month/:day/:title
      toc: true

toc:
  item_class: mnd-entry
  item_prefix: mnd-
  list_class: mnd-section
  list_id: null
  max_level: 2
  ordered_list: false

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

webrick:
  headers:
    Cache-Control: must-revalidate

exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - node_modules/
  - package-lock.json
  - package.json
  - README.MD
  - sendevia.page.jekyll.code-workspace
  - tsconfig.json
  - vendor/
  - webpack.config.js
  - webpack/

version: "23.615.0"
