timezone: Asia/Shanghai
title: sendevia 的博客

email: me@sendevia.top
github: https://github.com/Sendevia
twitter: https://twitter.com/sendevia

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

defaults:
  - scope:
      path: "_posts"
    values:
      toc: true

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - _redirects
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - readme.md
  - sendevia.page.jekyll.code-workspace
  - tsconfig.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
