title: AincradMix
email: sendevialol@gmail.com
github: https://github.com/Sendevia/AincradMix
timezone: Asia/Shanghai
current_version: release1.0

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - readme.md
