timezone: Asia/Shanghai
title: sendevia 的博客

current_version_amix: release1.0
email: me@sendevia.top
github_amix: https://github.com/Sendevia/AincradMix
twitter: https://twitter.com/sendevia

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-tsc

defaults:
  - scope:
      path: "_posts"
    values:
      toc: true

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - _redirects
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - readme.md
  - sendevia.github.io.code-workspace
  - tsconfig.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

typescript:
  cache: true
  command: ["tsc"]
  copy_ext: []
  extensions: [".ts", ".tsx"]
  temp_dir: .typescript
